version: '3.8'
services:
  db-mysql:
    image: mysql
    restart: always
    environment:
      - MYSQL_DATABASE=BE_nestjs
      - MYSQL_ROOT_PASSWORD=123456
      - TZ=Asia/Ho_Chi_Minh
    ports:
      - '3308:3306'
  minio:
    image: bitnami/minio:latest
    container_name: minio
    restart: always
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      - MINIO_ROOT_USER=tuanthanh
      - MINIO_ROOT_PASSWORD=tuanthanh123
